export const patternCardSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'PlaybookPatternCard',
  type: 'object',
  additionalProperties: false,
  required: [
    'schemaVersion',
    'kind',
    'patternId',
    'title',
    'status',
    'createdFromBucket',
    'trigger',
    'context',
    'mechanism',
    'invariant',
    'implication',
    'response',
    'examples',
    'evidence',
    'sourceKinds',
    'sourceRefs',
    'relatedModules',
    'relatedRules',
    'relatedDocs',
    'relatedOwners',
    'relatedTests',
    'relatedRiskSignals',
    'relatedGraphNodes',
    'relatedPatterns',
    'supersedes',
    'supersededBy',
    'reviewState',
    'promotionState',
    'confidence'
  ],
  properties: {
    schemaVersion: { const: '1.0' },
    kind: { const: 'playbook-pattern-card' },
    patternId: { type: 'string' },
    title: { type: 'string' },
    status: { enum: ['candidate', 'reviewed', 'promoted', 'archived'] },
    createdFromBucket: { enum: ['attach', 'merge', 'add'] },
    trigger: { type: 'string' },
    context: { type: 'string' },
    mechanism: { type: 'string' },
    invariant: { type: 'string' },
    implication: { type: 'string' },
    response: { type: 'string' },
    examples: { type: 'array', items: { type: 'string' } },
    evidence: { type: 'array', items: { type: 'string' } },
    sourceKinds: { type: 'array', items: { type: 'string' } },
    sourceRefs: { type: 'array', items: { type: 'string' } },
    relatedModules: { type: 'array', items: { type: 'string' } },
    relatedRules: { type: 'array', items: { type: 'string' } },
    relatedDocs: { type: 'array', items: { type: 'string' } },
    relatedOwners: { type: 'array', items: { type: 'string' } },
    relatedTests: { type: 'array', items: { type: 'string' } },
    relatedRiskSignals: { type: 'array', items: { type: 'string' } },
    relatedGraphNodes: { type: 'array', items: { type: 'string' } },
    relatedPatterns: { type: 'array', items: { type: 'string' } },
    supersedes: { type: 'array', items: { type: 'string' } },
    supersededBy: { type: 'array', items: { type: 'string' } },
    reviewState: { enum: ['pending-review', 'reviewed'] },
    promotionState: { enum: ['not-promoted', 'promoted'] },
    confidence: { type: ['number', 'null'] },
    notes: { type: 'string' }
  }
} as const;

export const patternCardReviewDraftSchema = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'PlaybookCompactionReviewDrafts',
  type: 'object',
  additionalProperties: false,
  required: ['schemaVersion', 'kind', 'generatedAt', 'summary', 'newCardsToReview', 'attachDecisions', 'mergeDecisions', 'addDecisions', 'discarded'],
  properties: {
    schemaVersion: { const: '1.0' },
    kind: { const: 'playbook-compaction-review-drafts' },
    generatedAt: { const: 'deterministic' }
  }
} as const;
